### ISSUE TITLE
Upstreaming

### ISSUE THREAD

**Issue by static-void** [revng/qemu#2]
Is this is still going to get upstreamed to qemu? It looks really cool but I'm concerned by the possibility of not being upstreamed or at least kept up to date with mainline qemu. Thanks

**Comment by aleclearmind** [comment]
Hi, we're working to [upstream](https://lists.gnu.org/archive/html/qemu-devel/2017-02/msg07556.html) the changes we made to QEMU. I'm also giving a talk about this at this year's [KVM forum](https://kvmforum2017.sched.com/event/Bnoh/libtcg-exposing-qemus-tcg-frontend-to-external-tools-alessandro-di-federico-politecnico-di-milano).

Feel free to get in touch with me directly for further information.

**Comment by franzflasch** [comment]
It seems this is still not upstreamed. What's the matter? This would really be an improvement for qemu. It's a pity, that the tcg can not be used as a standalone tool.

**Comment by aleclearmind** [comment]
We need to rebase and prettify our API so that it can be upstreamed.
Actually, if you have experience in QEMU/TCG, we're looking for people working on this and other related topics.

**Comment by franzflasch** [comment]
OK thanks for the answer. Unfortunately neither am I experienced with qemu (other than actually using it) nor am I experienced with TCG. However I am interested in using the TCG (without qemu) in one of my own projects. That's why I stumbled across your KVM talk on youtube and also this repo. Currently I am trying to gain knowledge about this topic.
